"""Quizzes generated by the AI 'quiz' job kind, plus user attempts.

A quiz is a *persisted* generation: the user can retake it later, and
each attempt accrues spaced-repetition state. The job that built it is
linked via job_id (nullable to allow manual quiz creation later).

scope_kind / scope_ref keep the audit trail of "what was this quiz built
from" — single note for Phase 3, way/topic/tag/multi for Phase 4. Stored
as text + JSON to avoid coupling to specific entity tables.

Revision ID: 023_ai_quizzes
Revises: 022_ai_jobs
Create Date: 2026-05-15
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = '023_ai_quizzes'
down_revision: Union[str, None] = '022_ai_jobs'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'ai_quizzes',
        sa.Column('id', sa.Uuid(as_uuid=True), primary_key=True),
        sa.Column(
            'user_id',
            sa.Uuid(as_uuid=True),
            sa.ForeignKey('users.id', ondelete='CASCADE'),
            nullable=False,
        ),
        sa.Column(
            'job_id',
            sa.Uuid(as_uuid=True),
            sa.ForeignKey('ai_jobs.id', ondelete='SET NULL'),
            nullable=True,
        ),
        # 'note' | 'topic' | 'way' | 'tag' | 'multi' | 'recent'
        sa.Column('scope_kind', sa.String(16), nullable=False),
        # Free-form scope payload: {note_id: ...} or {way_id: ...} etc.
        sa.Column('scope_ref', sa.JSON, nullable=False, server_default='{}'),
        # Display title cached for sidebar: "Quiz on 'NoteAttachment API'".
        sa.Column('title', sa.String(300), nullable=False),
        # The questions array (see schemas.ai.QuizQuestionOut for the shape).
        sa.Column('questions', sa.JSON, nullable=False),
        sa.Column('difficulty', sa.String(8), nullable=False, server_default='medium'),
        sa.Column(
            'created_at', sa.DateTime(timezone=True),
            server_default=sa.text('now()'), nullable=False,
        ),
    )
    op.create_index('ix_ai_quizzes_user_created', 'ai_quizzes', ['user_id', 'created_at'])

    op.create_table(
        'ai_quiz_attempts',
        sa.Column('id', sa.Uuid(as_uuid=True), primary_key=True),
        sa.Column(
            'quiz_id',
            sa.Uuid(as_uuid=True),
            sa.ForeignKey('ai_quizzes.id', ondelete='CASCADE'),
            nullable=False,
        ),
        sa.Column(
            'user_id',
            sa.Uuid(as_uuid=True),
            sa.ForeignKey('users.id', ondelete='CASCADE'),
            nullable=False,
        ),
        # Array of {question_idx, selected, correct}.
        sa.Column('answers', sa.JSON, nullable=False, server_default='[]'),
        sa.Column('score', sa.Integer, nullable=False, server_default='0'),
        sa.Column('total', sa.Integer, nullable=False),
        # Next time we'd surface this quiz for review. Computed from score.
        sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            'started_at', sa.DateTime(timezone=True),
            server_default=sa.text('now()'), nullable=False,
        ),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index('ix_ai_quiz_attempts_quiz', 'ai_quiz_attempts', ['quiz_id'])


def downgrade() -> None:
    op.drop_index('ix_ai_quiz_attempts_quiz', table_name='ai_quiz_attempts')
    op.drop_table('ai_quiz_attempts')
    op.drop_index('ix_ai_quizzes_user_created', table_name='ai_quizzes')
    op.drop_table('ai_quizzes')
